
version: 2

models:
    - name: country_table
      description: "A starter dbt model"
      columns:
          - name: country_name
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    # - name: country
    #   description: "A starter dbt model"
    #   columns:
    #       - name: country_code
    #         description: "The primary key for this table"
    #         tests:
    #             - unique
    #             - not_null
    #             - accepted_values:
    #                   values: ['US', 'CA', 'GB']